version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres:14
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
